version: "3.9"

services:
   holx-gdds:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/holx-gdds:cached
    command: sleep infinity
    ports:
      - "3000:3000"
